
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube021: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Sphere: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere002: THREE.Mesh
    Sphere003: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']): JSX.Element {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/calculator.gltf') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.01, -0.21]} scale={[1, 1, 0.58]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-0.72, 1.19, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-0.72, 1.01, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-0.72, 0.83, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-0.72, 0.64, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-0.72, 0.44, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-0.72, 0.24, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-0.42, 1.19, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-0.42, 1.01, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-0.42, 0.83, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-0.42, 0.64, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-0.42, 0.44, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-0.42, 0.24, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-0.18, 1.19, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-0.18, 1.01, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[-0.18, 0.83, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[-0.18, 0.64, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[-0.18, 0.44, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-0.18, 0.24, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[0.07, 1.19, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[0.07, 1.01, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[0.07, 0.83, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[0.07, 0.64, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[0.07, 0.44, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[0.07, 0.24, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[0.34, 1.19, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[0.34, 1.01, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[0.34, 0.83, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[0.34, 0.64, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        position={[0.34, 0.44, 0.16]}
        scale={[0.12, 0.06, 0.25]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-0.67, 1.37, 0.37]}
        scale={[0.11, 0.06, 0.05]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[-0.26, 1.37, 0.37]}
        scale={[0.09, 0.05, 0.04]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[0.01, 1.37, 0.37]}
        scale={[0.09, 0.05, 0.04]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[0.25, 1.37, 0.37]}
        scale={[0.09, 0.05, 0.04]}
      />
    </group>
  )
}

useGLTF.preload('/calculator.gltf')